const MONGO_URI = process.env.MONGO_URI,
  MONGO_URI_TEST = process.env.MONGO_URI_TEST,
  MONGO_URI_DEV = process.env.MONGO_URI_DEV,
  MONGO_URI_PROD = process.env.MONGO_URI_PROD;

const PORT = process.env.PORT;

/* JWT TOKENS */
const JWT_SECRET = process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET,
  JWT_SECRET_EXP = process.env.JWT_ACCESS_EXP,
  JWT_ACCESS_EXP = process.env.JWT_ACCESS_EXP,
  JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXP = process.env.JWT_REFRESH_EXP,
  JWT_PASSWORDRESET_SECRET = process.env.JWT_PASSWORDRESET_SECRET,
  JWT_PASSWORDRESET_EXP = process.env.JWT_PASSWORDRESET_EXP,
  JWT_EMAILVERIFICATION_SECRET = process.env.JWT_EMAILVERIFICATION_SECRET,
  JWT_EMAILVERIFICATION_EXP = process.env.JWT_EMAILVERIFICATION_EXP,
  JWT_SUPERADMINACTIVATION_SECRET = process.env.JWT_SUPERADMINACTIVATION_SECRET,
  JWT_SUPERADMINACTIVATION_EXP = process.env.JWT_SUPERADMINACTIVATION_EXP;

/* EMAIL and OAUTH2*/
const EMAIL_HOST = process.env.EMAIL_HOST,
  EMAIL_PORT = process.env.EMAIL_PORT,
  EMAIL_PASS = process.env.EMAIL_PASS,
  EMAIL_HOST_ADDRESS = process.env.EMAIL_HOST_ADDRESS,
  OAUTH_CLIENT_ID = process.env.OAUTH_CLIENT_ID,
  OAUTH_CLIENT_SECRET = process.env.OAUTH_CLIENT_SECRET,
  OAUTH_REFRESH_TOKEN = process.env.OAUTH_REFRESH_TOKEN,
  OAUTH_ACCESS_TOKEN = process.env.OAUTH_ACCESS_TOKEN,
  GOOGLE_SIGNIN_CLIENT_ID = process.env.GOOGLE_SIGNIN_CLIENT_ID,
  HOST_ADMIN_EMAIL1 = process.env.HOST_ADMIN_EMAIL1,
  HOST_ADMIN_EMAIL2 = process.env.HOST_ADMIN_EMAIL2,
  ADMIN_EMAIL = process.env.ADMIN_EMAIL,
  ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

/* Server */
const SERVER_URL = process.env.SERVER_URL,
  CLIENT_APP_URL = process.env.CLIENT_APP_URL;

/* Github */
const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET;

/* Cloudinary */
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

/* CROWDIN */
const CROWDIN_API_KEY = process.env.CROWDIN_API_KEY,
  CROWDIN_PROJECT_ID = process.env.CROWDIN_PROJECT_ID,
  CROWDIN_API = process.env.CROWDIN_API,
  CROWDIN_MTS_ID = process.env.CROWDIN_MTS_ID;

module.exports = {
  // MongoDB URI
  MONGO_URI,
  MONGO_URI_TEST,
  MONGO_URI_DEV,
  MONGO_URI_PROD,

  // Server Port
  PORT,

  // JWT Tokens
  JWT_SECRET,
  JWT_SECRET_EXP,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACCESS_EXP,
  JWT_REFRESH_EXP,
  JWT_PASSWORDRESET_SECRET,
  JWT_PASSWORDRESET_EXP,
  JWT_EMAILVERIFICATION_SECRET,
  JWT_EMAILVERIFICATION_EXP,
  JWT_SUPERADMINACTIVATION_SECRET,
  JWT_SUPERADMINACTIVATION_EXP,

  // Email
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_HOST_ADDRESS,
  EMAIL_PASS,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,

  // OAUTH2
  OAUTH_CLIENT_ID,
  OAUTH_CLIENT_SECRET,
  OAUTH_REFRESH_TOKEN,
  OAUTH_ACCESS_TOKEN,
  GOOGLE_SIGNIN_CLIENT_ID,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  HOST_ADMIN_EMAIL1,
  HOST_ADMIN_EMAIL2,

  // Server
  SERVER_URL,
  CLIENT_APP_URL,

  // Cloudinary
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,

  // CROWDIN
  CROWDIN_API_KEY,
  CROWDIN_PROJECT_ID,
  CROWDIN_API,
  CROWDIN_MTS_ID,
};
