name: Merge Crowdin branch into frontend-ui

on:
  pull_request:
    branches: [frontend-ui]

  workflow_dispatch:

jobs:
  merge:
    needs: pull-request
    name: merge
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          source: "test-branch"
          target: "frontend-ui"
